### ISSUE TITLE
[dev] Nuxt.js vs NuxtJS vs Nuxt

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxtjs.org#402]
Hey all 👋 

at the moment, the terms **Nuxt.js**, **Nuxt** and **NuxtJS** are not used consistently, nor they are "explained" somewhere.

From my current understanding, these terms are used like that:

* The *framework* = **Nuxt.js**
* The *company* = **NuxtJS**
* "Colloqiually" referrencing to the Framework and ecosystem (should be avoided) = **Nuxt**

---

## Questions

1. Is this still correct?
2. Because many people (still) think that **NuxtJS** === **Nuxt.js**, could we somewhere explain the terms correctly?
3. Would you accept PRs to fix the terminology in case 1. is answered with "yes"?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c231">#c231</a>)</em></sub></div>

**Comment by danielroe** [comment]
That's my read too. If `NuxtJS` is used for the company, I think it needs a little `?` icon or `<abbr>` popup that explains this.

**Comment by debs-obrien** [comment]
Nuxt.js for framework and NuxtJS for company, correct. There were 2 instances in docs that had NuxtJS instead of Nuxt.js and that is now corrected. Nuxt can be used throughout documentation as it is explaining features, commands etc so using Nuxt is ok as we wouldn't say the Nuxt.js generate command as the Nuxt generate command sounds better here. Also Nuxt server etc. But referencing the framework for example with Nuxt.js you can put your page in a pages folder.... I like to think of it as as if I was writing Nuxt.js it would be the same as writing The Nuxt.js framework so to go with my example above it doesn't make sense to say The Nuxt.js framework generate command. So throughout the documentation that is what I have used so it should be consistent however if you find a place where it isn't then feel free to correct it. The new site has not been done and we have only worked on the guides section of the website and not any other so there will be inconsistencies with the old content which will be worked on when new site is released. But for sure a lot of the plugins/modules might need updating. 

Regarding question 2 I will talk with Alex about that and where it makes sense to do that.

**Comment by debs-obrien** [comment]
We will have dedicated pages (discover section) in the new website to explain how the NuxtJS company was created with the success of the Nuxt.js framework.

**Comment by manniL** [comment]
> Nuxt.js for framework and NuxtJS for company, correct.

Great 👍🏻

> Nuxt can be used throughout documentation as it is explaining features, commands etc so using Nuxt is ok as we wouldn't say the Nuxt.js generate command as the Nuxt generate command sounds better here. Also Nuxt server etc.

Definitely, makes sense 👍🏻 "Nuxt.js generate command" would sound weird, indeed.


>  The new site has not been done and we have only worked on the guides section of the website and not any other so there will be inconsistencies with the old content which will be worked on when new site is released. But for sure a lot of the plugins/modules might need updating.

No worries! I only wanted to bring that topic up early so we all can apply the right terms from the start on 😋


> We will have dedicated pages (discover section) in the new website to explain how the NuxtJS company was created with the success of the Nuxt.js framework.

Sounds good 👍🏻

**Comment by pimlie** [comment]
If this is the case shouldnt the logo of the opensource framework also use a dot an lowercase js and not the company name?

**Comment by alexchopin** [comment]
Hello everyone!
As it seems still not clear and important for some of you about the terminology, here more details:
Nuxt.js is the name of the Open source framework based on Vue.js.
Like most of JS project, we use to write/say the name of the project (Nuxt) without ".js" like Vue, React and more.
The NuxtJS company (originally named Orion at the early stage) is the company created by the creators of Nuxt.js (my brother @Atinux and I) to work full time on the Nuxt development (Framework, Documentation, Advocating, Training, Consultancy and more). We love to Open Source our projects and our code base, but the lead and the direction of the framework development still remain to the NuxtJS company.
Cheers!

**Comment by manniL** [comment]
Thanks for clarifying the wording Alex 👍🏻

> As it seems still not clear and important for some of you about the terminology, here more details

It is mostly important to me because not everyone is as "involved" as many of us are. I'm mostly worrying that people will use Nuxt.js and NuxtJS *interchangeably* and **think that these terms mean the same "thing"**, which they obviously do not. 

To avoid that people make such a mistake, especially those who had just a few touch points with the framework, I wanted to clear that up and follow up fixing terminology (e.g. via #403).

From my POV, it might pose an underestimated challenge to separate the two meaning so the clearer we make the cut, the better we manage it 😋

**Comment by danielroe** [comment]
From a communications perspective, it might be easier and less confusing to use Nuxt.js and NuxtJS interchangeably, and just make a distinction between the NuxtJS _framework_ and the NuxtJS _company_, where relevant.

**Comment by sebmellen** [comment]
Hope it's alright to add a comment...

- [x] @danielroe from my perspective as a user, this is the clearest way to differentiate. 

One way to do this is to attach the name of the company form when referencing the company. For example, as opposed to "NuxtJS", you could say "NuxtJS SARL/GmbH/Inc./etc.". 

This makes it clear you are referencing the company, and also offers different naming that translates over to non-text formats. As an example, if you are giving a voice interview, it is hard to differentiate between "Nuxt.js and NuxtJS". On the other hand, if you say "**Nuxt SARL** recently raised a $2M seed round to build the **_Nuxt.js_** framework", this is very clear. 

I hope that makes sense. Great project, and congrats on the raise!

**Comment by Atinux** [comment]
Thank you for your feedbacks.

Anytime we want to mention the company, it will be with NuxtJS Company (or NuxtJS SAS like @sebmellen suggested).

So you will mostly see NuxtJS Company and Nuxt.js Framework (or Nuxt Framework).
